### ISSUE TITLE
Add leave room mechanism during round

### ISSUE THREAD

**Issue by eduardhuck** [fafeitsch/city-knowledge-contest#14]
To start a new room, you currently have to manually edit the URL and delete the room part.

Add a button for the user to leave the current room and navigate back to the start page.
The user should be removed from the player list for every other user still in the room.

The backend should consider closing the room, after the last player left.

**Comment by fafeitsch** [comment]
done by pr#16

**Comment by fafeitsch** [comment]
done by pr#16
